blank_issues_enabled: true
contact_links:
  - name: CIME issue
    url: https://github.com/CMCC-Foundation/cime/issues/new/choose
    about: Issue with CIME (scripting infrastructure, share code, etc.)
  - name: CAM issue
    url: https://github.com/CMCC-Foundation/CAM/issues/new/choose
    about: Issue with CAM (Community Atmosphere Model)
  - name: CTSM / CLM issue
    url: https://github.com/CMCC-Foundation/CTSM/issues/new/choose
    about: Issue with CTSM / CLM (Community Terrestrial Systems Model / Community Land Model) in CMCC-CM
  - name: NEMO issue
    url: https://github.com/CMCC-Foundation/NEMO-CESM/issues/new
    about: Issue with NEMO in CMCC-CM
  - name: CICE6 issue
    url: https://github.com/CMCC-Foundation/CICE-CESM2/issues/new/choose
    about: Issue with CICE6 in CMCC-CM
  - name: CISM issue
    url: https://github.com/CMCC-Foundation/cism-wrapper/issues/new/choose
    about: Issue with CISM (Community Ice Sheet Model) in CMCC-CM
  - name: MOSART issue
    url: https://github.com/CMCC-Foundation/MOSART/issues/new/choose
    about: Issue with MOSART in CESM (Model for Scale Adaptive River Transport)
  - name: RTM issue
    url: https://github.com/CMCC-Foundation/RTM/issues/new/choose
    about: Issue with RTM (River Transport Model)
  - name: WW3 issue
    url: https://github.com/CMCC-Foundation/WW3-CESM/issues/new/choose
    about: Issue with WW3 in CESM (WaveWatch III)
  - name: CMEPS issue
    url: https://github.com/CMCC-Foundation/CMEPS/issues/new/choose
    about: Issue with CMEPS (NUOPC Community Mediator for Earth Prediction Systems)
  - name: CDEPS issue
    url: https://github.com/CMCC-Foundation/CDEPS/issues/new/choose
    about: Issue with CDEPS (Community Data Models for Earth Prediction Systems)
  - name: ccs_config_cmcc issue
    url: https://github.com/CMCC-Foundation/ccw_config_cmcc/issues/new/choose
    about: Issue with configuration of CMCC supported grids, servers, and compilers.
  - name: share code issue
    url: https://github.com/CMCC-Foundation/CMCC_share/issues/new/choose
    about: Issue with configuration of CMCC supported grids, servers, and compilers.
